In [22]:
import pandas as pd
import numpy as np
import sqlite3
import time

In [3]:
#creating database connection
conn = sqlite3.connect('inventory.db')

In [4]:
# checking the table stored in the database
tables = pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table'",conn)
tables

              name
0  begin_inventory
1    end_inventory
2        purchases
3  purchase_prices
4            sales
5   vendor_invoice

In [5]:
for table in tables['name'] :
    print('-'*50, f'{table}','-'*50) # it will print ---------------------table_name-----------------------
    print('Count of records:',pd.read_sql(f"select count(*) as count from {table} " , conn)['count'].values[0])
    display(pd.read_sql(f"select * from {table} limit 5", conn))

-------------------------------------------------- begin_inventory --------------------------------------------------
Count of records: 206529

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,startDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,8,12.99,2024-01-01
1,1_HARDERSFIELD_60,1,HARDERSFIELD,60,Canadian Club 1858 VAP,750mL,7,10.99,2024-01-01
2,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,6,36.99,2024-01-01
3,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,3,38.99,2024-01-01
4,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,6,34.99,2024-01-01

-------------------------------------------------- end_inventory --------------------------------------------------
Count of records: 224489

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,endDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,11,12.99,2024-12-31
1,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,7,36.99,2024-12-31
2,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,7,38.99,2024-12-31
3,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,4,34.99,2024-12-31
4,1_HARDERSFIELD_75,1,HARDERSFIELD,75,Three Olives Tomato Vodka,750mL,7,14.99,2024-12-31

-------------------------------------------------- purchases --------------------------------------------------
Count of records: 2372474

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,69_MOUNTMEND_8412,69,8412,Tequila Ocho Plata Fresno,750mL,105,ALTAMAR BRANDS LLC,8124,2023-12-21,2024-01-02,2024-01-04,2024-02-16,35.71,6,214.26,1
1,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
2,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
3,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
4,76_DONCASTER_2034,76,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,8169,2023-12-24,2024-01-02,2024-01-09,2024-02-16,21.32,5,106.60,1

-------------------------------------------------- purchase_prices --------------------------------------------------
Count of records: 12261

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.

-------------------------------------------------- sales --------------------------------------------------
Count of records: 12825363

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-01,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
1,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,2,32.98,16.49,2024-01-02,750.0,1,1.57,12546,JIM BEAM BRANDS COMPANY
2,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-03,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
3,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,14.49,14.49,2024-01-08,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
4,1_HARDERSFIELD_1005,1,1005,Maker's Mark Combo Pack,375mL 2 Pk,2,69.98,34.99,2024-01-09,375.0,1,0.79,12546,JIM BEAM BRANDS COMPANY

-------------------------------------------------- vendor_invoice --------------------------------------------------
Count of records: 5543

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.47,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
2,388,ATLANTIC IMPORTING COMPANY,2024-01-09,8169,2023-12-24,2024-02-16,5,106.60,4.61,None
3,480,BACARDI USA INC,2024-01-12,8106,2023-12-20,2024-02-05,10100,137483.78,2935.20,None
4,516,BANFI PRODUCTS CORP,2024-01-07,8170,2023-12-24,2024-02-12,1935,15527.25,429.20,None

In [6]:
purchases = pd.read_sql_query("""select * from purchases where VendorNumber = 4466""", conn)
purchases

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
1,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
2,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
3,38_GOULCREST_5215,38,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8207,2023-12-27,2024-01-07,2024-01-19,2024-02-26,9.41,6,56.46,1
4,59_CLAETHORPES_5215,59,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8207,2023-12-27,2024-01-05,2024-01-19,2024-02-26,9.41,6,56.46,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2187,81_PEMBROKE_5215,81,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-29,2025-01-04,2025-02-10,9.41,6,56.46,1
2188,62_KILMARNOCK_5255,62,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-28,2025-01-04,2025-02-10,9.35,5,46.75,1
2189,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-28,2025-01-04,2025-02-10,9.41,5,47.05,1
2190,6_GOULCREST_5215,6,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-31,2025-01-04,2025-02-10,9.41,6,56.46,1
2191,35_HALIVAARA_5255,35,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-27,2025-01-04,2025-02-10,9.35,5,46.75,1

In [7]:
vendor_invoice = pd.read_sql_query('Select * from Vendor_invoice where VendorNumber = 4466', conn)

In [8]:
purchase_prices = pd.read_sql_query("""select * from purchase_prices where VendorNumber = 4466""", conn)
purchase_prices

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,5215,TGI Fridays Long Island Iced,12.99,1750mL,1750,1,9.41,4466,AMERICAN VINTAGE BEVERAGE
1,5255,TGI Fridays Ultimte Mudslide,12.99,1750mL,1750,1,9.35,4466,AMERICAN VINTAGE BEVERAGE
2,3140,TGI Fridays Orange Dream,14.99,1750mL,1750,1,11.19,4466,AMERICAN VINTAGE BEVERAGE

In [9]:
sales = pd.read_sql_query("select * from sales where VendorNo = 4466",conn)
sales

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-09,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
1,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-12,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
2,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-15,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
3,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-21,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
4,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-23,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9448,9_BLACKPOOL_5215,9,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-12-21,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
9449,9_BLACKPOOL_5255,9,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-12-02,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
9450,9_BLACKPOOL_5255,9,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-12-09,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
9451,9_BLACKPOOL_5255,9,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-12-23,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
9452,9_BLACKPOOL_5255,9,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-12-31,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE

In [10]:
sales.groupby('Brand')[['SalesDollars','SalesPrice','SalesQuantity']].sum()

       SalesDollars  SalesPrice  SalesQuantity
Brand
3140       50531.10    30071.85           3890
5215       60416.49    41542.02           4651
5255       79187.04    51180.60           6096

In [11]:
purchases.groupby(['Brand' , 'PurchasePrice'], as_index = False)[['Quantity' , 'Dollars']].sum()

   Brand  PurchasePrice  Quantity   Dollars
0   3140          11.19      4640  51921.60
1   5215           9.41      4923  46325.43
2   5255           9.35      6215  58110.25

In [12]:
vendor_invoice['PONumber'].nunique()

55

BRAND INSIGHT :
  
:- The purchases table contain actual purchase data, including the date of purchase , products (brands) purchased by vendors, the amount paid (in dollars), and the quantity purchased.

:- The purchase price column is derived from the purchase_prices table, which provides product-wise actual and purchase prices. The combination of vendor and brand is unique in this table.

:-The vendor_invoice table aggregates data from the purchases table, summarizing quantity and dollar amounts, along with an additional column for freight. This table maintains uniqueness based on vendor and PO(Purchased Order ) number.

:-The sales table captures actual sales transactions, detailing the brands purchased by vendors, the quantity sold, the selling price, and the revenue earned.
______________________________________________________________________________

As the data that we need for analysis is distributed in different tables, we need to create a summary table containing:

:- purchase transcations made by vendors

:- sales transaction data

:- freight costs for each vendors

:- actual product prices from vendors

In [23]:
vendor_invoice.columns

Index(['VendorNumber', 'VendorName', 'InvoiceDate', 'PONumber', 'PODate',
       'PayDate', 'Quantity', 'Dollars', 'Freight', 'Approval'],
      dtype='object')

In [27]:
freight_summary = pd.read_sql_query('''Select vi.VendorNumber, SUM(vi.Freight) as TotalFreightCost,
                                    sum(vi.Dollars) as TotalPurchaseDollars,
                                    sum(vi.Quantity) as TotalPurchaseQuantity
                                    From vendor_invoice as vi
                                    Group BY VendorNumber ''',conn)
freight_summary

,VendorNumber,TotalFreightCost,TotalPurchaseDollars,TotalPurchaseQuantity
0,2,27.08,5630.88,328
1,54,0.48,105.07,1
2,60,367.52,76770.25,4732
3,105,62.39,11706.20,332
4,200,6.19,1205.16,132
...,...,...,...,...
121,98450,856.02,168993.61,10463
122,99166,130.09,25961.04,1212
123,172662,178.34,34708.03,1629
124,173357,202.50,41036.44,1990
125,201359,0.09,17.00,1

In [15]:
pd.read_sql_query("""SELECT p.VendorNumber,
                    p.VendorName, p.Brand, p.PurchasePrice,
                  pp.Volume,
                  pp.Price as ActualPrice,
                  SUM(Quantity) as TotalPurchaseQuantity,
                  Sum(Dollars) as TotalPurchaseDollars
                  FROM purchases p
                  JOIN purchase_prices pp
                    On p.Brand = pp.Brand
                  Where p.PurchasePrice > 0
                  GROUP BY p.VendorNumber , p.VendorName, p.Brand
                  Order By TotalPurchaseDollars""", conn)

,VendorNumber,VendorName,Brand,PurchasePrice,Volume,ActualPrice,TotalPurchaseQuantity,TotalPurchaseDollars
0,7245,PROXIMO SPIRITS INC.,3065,0.71,50,0.99,1,0.71
1,3960,DIAGEO NORTH AMERICA INC,6127,1.47,200,1.99,1,1.47
2,3924,HEAVEN HILL DISTILLERIES,9123,0.74,50,0.99,2,1.48
3,8004,SAZERAC CO INC,5683,0.39,50,0.49,6,2.34
4,9815,WINE GROUP INC,8527,1.32,750,4.99,2,2.64
...,...,...,...,...,...,...,...,...
10687,3960,DIAGEO NORTH AMERICA INC,3545,21.89,1750,29.99,138109,3023206.01
10688,3960,DIAGEO NORTH AMERICA INC,4261,16.17,1750,22.99,201682,3261197.94
10689,17035,PERNOD RICARD USA,8068,18.24,1750,24.99,187407,3418303.68
10690,4425,MARTIGNETTI COMPANIES,3405,23.19,1750,28.99,164038,3804041.22
10691,1128,BROWN-FORMAN CORP,1233,26.27,1750,36.99,145080,3811251.60

In [16]:
sales.columns

Index(['InventoryId', 'Store', 'Brand', 'Description', 'Size', 'SalesQuantity',
       'SalesDollars', 'SalesPrice', 'SalesDate', 'Volume', 'Classification',
       'ExciseTax', 'VendorNo', 'VendorName'],
      dtype='object')

In [ ]:
pd.read_sql_query("""Select VendorNo,
                  Brand,
                  SUM(s.Salesprice) as TotalSalesprice,
                  SUM(s.SalesDollars) as TotalSalesDollars,
                  SUM(s.SalesQuantity) as TotalSalesQuantity,
                  SUM(s.ExciseTax) as TotalExciseTax
                  From sales s
                  Group BY VendorNo, Brand
                  Order BY TotalSalesDollars""", conn)

,VendorNo,Brand,TotalSalesprice,TotalSalesDollars,TotalSalesQuantity,TotalExciseTax
0,8004,5287,0.98,0.98,2,0.10
1,9206,2773,0.99,0.99,1,0.05
2,3252,3933,0.99,1.98,2,0.10
3,3924,9123,0.99,1.98,2,0.10
4,10050,3623,1.98,1.98,2,0.10
...,...,...,...,...,...,...
11267,3960,3545,545778.28,4223107.62,135838,249587.83
11268,3960,4261,420050.01,4475972.88,200412,368242.80
11269,17035,8068,461140.15,4538120.60,187140,343854.07
11270,4425,3405,561512.37,4819073.49,160247,294438.66
11271,1128,1233,672819.31,5101919.51,142049,260999.20

In [ ]:
start = time.time()
final_table = pd.read_sql_query("""Select
pp.VendorNumber,
pp.Brand,
pp. Price as ActualPrice,
SUM(s.Salesprice) as TotalSalesprice,
SUM(s.SalesDollars) as TotalSalesDollars,
SUM(s.SalesQuantity) as TotalSalesQuantity,
SUM(s.ExciseTax) as TotalExciseTax,
SUM(vi.Freight) as TotalFreightCost,
sum(vi.Dollars) as TotalPurchaseDollars,
sum(vi.Quantity) as TotalPurchaseQuantity
From purchase_prices pp
Join sales s
   ON pp.VendorNumber = s.VendorNo
   AND pp.Brand = s.Brand
Join vendor_invoice vi
   On pp.VendorNumber = vi.VendorNumber
Group BY pp.VendotNumber, pp.Brand, pp.Price, pp.PuchasePrice
   """)

end = time.time

In [33]:
vendor_sales_summary = pd.read_sql_query("""With FreightSummary AS(Select  VendorNumber, SUM(Freight) as TotalFreightCost
                                    
                                    From vendor_invoice  
                                    Group BY VendorNumber ),
                                         
PurchaseSummary AS (
 Select  p.VendorNumber, p.VendorName, p.Brand,p.Description, p.PurchasePrice,
pp.Price as ActualPrice, pp.volume,
SUM(Quantity) as TotalPurchaseQuantity,
Sum(Dollars) as TotalPurchaseDollars     
FROM purchases p
JOIN purchase_prices pp
    On p.Brand = pp.Brand
Where p.PurchasePrice > 0
GROUP BY p.VendorNumber , p.VendorName, p.Brand, p.Description, p.PurchasePrice, pp.Price, pp.Volume),

SalesSummary AS( Select VendorNo,Brand,SUM(SalesPrice) as TotalSalesprice,
                  SUM(SalesDollars) as TotalSalesDollars,
                  SUM(SalesQuantity) as TotalSalesQuantity,
                  SUM(ExciseTax) as TotalExciseTax
        FROM sales
        Group By VendorNo, Brand
)
                                         
Select ps.VendorNumber, ps.VendorName, ps.Brand,ps.Description, ps.PurchasePrice,
ps.ActualPrice, ps.Volume, ps.TotalPurchaseQuantity,ps.TotalPurchaseDollars,
ss.TotalSalesprice, ss.TotalSalesDollars, ss.TotalSalesQuantity, ss.TotalExciseTax,fs.TotalFreightCost
From PurchaseSummary ps
Left join SalesSummary ss
 ON ps.VendorNumber = ss.VendorNo
 AND ps.Brand = ss.Brand
Left Join FreightSummary fs
    ON ps.VendorNumber = fs.VendorNumber
Order BY ps.totalPurchaseDollars DESC""", conn)

In [ ]:
vendor_sales_summary
# this is our aggregated table

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesprice,TotalSalesDollars,TotalSalesQuantity,TotalExciseTax,TotalFreightCost
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750,145080,3811251.60,672819.31,5101919.51,142049.0,260999.20,68601.68
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750,164038,3804041.22,561512.37,4819073.49,160247.0,294438.66,144929.24
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750,187407,3418303.68,461140.15,4538120.60,187140.0,343854.07,123780.22
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750,201682,3261197.94,420050.01,4475972.88,200412.0,368242.80,257032.07
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750,138109,3023206.01,545778.28,4223107.62,135838.0,249587.83,257032.07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,9815,WINE GROUP INC,8527,Concannon Glen Ellen Wh Zin,1.32,4.99,750,2,2.64,10.96,15.95,5.0,0.55,27100.41
10688,8004,SAZERAC CO INC,5683,Dr McGillicuddy's Apple Pie,0.39,0.49,50,6,2.34,1.47,65.66,134.0,7.04,50293.62
10689,3924,HEAVEN HILL DISTILLERIES,9123,Deep Eddy Vodka,0.74,0.99,50,2,1.48,0.99,1.98,2.0,0.10,14069.87
10690,3960,DIAGEO NORTH AMERICA INC,6127,The Club Strawbry Margarita,1.47,1.99,200,1,1.47,77.61,143.28,72.0,15.12,257032.07
10691,7245,PROXIMO SPIRITS INC.,3065,Three Olives Grape Vodka,0.71,0.99,50,1,0.71,33.66,85.14,86.0,4.46,38994.78

This query generates a vendor-wise sales and purchase summary, which is valuable for:

Performance Optimization :

:- The query invovles heavy joins and aggregation on large datasets like sales and purchases.

:- Storing the pre-aggregated results avoids repeated expensive computations.

:- Helps in analzing sales, purchases, and pricing for different vendors and brands.

:- Future benefits of storing this data for faster Dashboarding & Reporting.

:- instead of running expensive queries each time, dashboards can fetch data qucikly from vendor_sales_summary

In [44]:
vendor_sales_summary.dtypes

VendorNumber               int64
VendorName                object
Brand                      int64
Description               object
PurchasePrice            float64
ActualPrice              float64
volume                   float64
TotalPurchaseQuantity      int64
TotalPurchaseDollars     float64
TotalSalesprice          float64
TotalSalesDollars        float64
TotalSalesQuantity       float64
TotalExciseTax           float64
TotalFreightCost         float64
dtype: object

In [43]:
vendor_sales_summary.isnull().sum()

VendorNumber             0
VendorName               0
Brand                    0
Description              0
PurchasePrice            0
ActualPrice              0
volume                   0
TotalPurchaseQuantity    0
TotalPurchaseDollars     0
TotalSalesprice          0
TotalSalesDollars        0
TotalSalesQuantity       0
TotalExciseTax           0
TotalFreightCost         0
dtype: int64

In [42]:
vendor_sales_summary['VendorName'].unique()

array(['BROWN-FORMAN CORP', 'MARTIGNETTI COMPANIES', 'PERNOD RICARD USA',
       'DIAGEO NORTH AMERICA INC', 'BACARDI USA INC',
       'JIM BEAM BRANDS COMPANY', 'MAJESTIC FINE WINES',
       'ULTRA BEVERAGE COMPANY LLP', 'STOLI GROUP,(USA) LLC',
       'PROXIMO SPIRITS INC.', 'MOET HENNESSY USA INC', 'CAMPARI AMERICA',
       'SAZERAC CO INC', 'CONSTELLATION BRANDS INC', 'M S WALKER INC',
       'SAZERAC NORTH AMERICA INC.', 'PALM BAY INTERNATIONAL INC',
       'REMY COINTREAU USA INC', 'SIDNEY FRANK IMPORTING CO',
       'E & J GALLO WINERY', 'WILLIAM GRANT & SONS INC',
       'HEAVEN HILL DISTILLERIES', 'DISARONNO INTERNATIONAL LLC',
       'EDRINGTON AMERICAS', 'CASTLE BRANDS CORP.',
       'SOUTHERN WINE & SPIRITS NE', 'STE MICHELLE WINE ESTATES',
       'TRINCHERO FAMILY ESTATES', 'MHW LTD', 'WINE GROUP INC',
       'PERFECTA WINES', 'LUXCO INC', 'TREASURY WINE ESTATES',
       'DIAGEO CHATEAU ESTATE WINES', 'SHAW ROSS INT L IMP LTD',
       'PINE STATE TRADING CO', 'PHILLIPS PRODUCTS CO.',
       'CALEDONIA SPIRITS INC', 'STATE WINE & SPIRITS',
       'KOBRAND CORPORATION', 'BANFI PRODUCTS CORP',
       'VINEYARD BRANDS INC', 'DELICATO VINEYARDS INC',
       'FABRIZIA SPIRITS LLC', 'DUGGANS DISTILLED PRODUCTS',
       'Serralles Usa LLC', 'SEA HAGG DISTILLERY LLC',
       'OLE SMOKY DISTILLERY LLC', 'VRANKEN AMERICA', 'KLIN SPIRITS LLC',
       'LAIRD & CO', 'ADAMBA IMPORTS INTL INC',
       'LATITUDE BEVERAGE COMPANY', 'FREDERICK WILDMAN & SONS',
       'MCCORMICK DISTILLING CO', 'CHARLES JACQUIN ET CIE INC',
       'WESTERN SPIRITS BEVERAGE CO', 'MARSALLE COMPANY',
       'AMERICAN VINTAGE BEVERAGE', 'MANGO BOTTLING INC',
       'SWEET BABY VINEYARD', 'NICHE W & S', 'LABELLE VYDS AND WINERY',
       'FLAG HILL WINERY & VINEYARD', 'SMOKY QUARTZ DISTILLERY LLC',
       'PREMIUM PORT WINES, INC.', 'Russian Standard Vodka',
       'Dunn Wine Brokers', 'WEIN BAUER INC', 'BULLY BOY DISTILLERS',
       'ATLANTIC IMPORTING COMPANY', 'PREMIER DISTRIBUTORS',
       'VINILANDIA USA', 'PARK STREET IMPORTS LLC', 'TAKARA SAKE USA INC',
       'SEA BREEZE CELLARS LLC', 'STARK BREWING COMPANY', 'TY KU LLC',
       'PSP WINES', 'TAMWORTH DISTILLING', 'ZORVINO VINEYARDS',
       'SOUTHERN GLAZERS W&S OF NE', 'HOOD RIVER DISTILLERS, Inc.',
       'CRUSH WINES', 'POVERTY LANE ORCHARDS', 'DJINN SPIRITS LLC',
       'MOONLIGHT MEADERY', 'TALL SHIP DISTILLERY LLC',
       'FORTUNE WINE BROKERS LLC', 'BLACK COVE BEVERAGES', 'VINEXTRA INC',
       'SURVILLE ENTERPRISES CORP', 'JEWELL TOWNE VINEYARDS',
       'SWEETWATER FARM', 'ALTAMAR BRANDS LLC', 'CANDIA VINEYARDS',
       'INCREDIBREW INC', 'ALISA CARR BEVERAGES',
       'STELLAR IMPORTING CO LLC', 'FULCHINO VINEYARD INC',
       'IRA GOLDMAN AND WILLIAMS, LLP', 'Circa Wines',
       'VINEDREA WINES LLC', 'BLACK PRINCE DISTILLERY INC',
       'VINEYARD BRANDS LLC', 'THE IMPORTED GRAPE LLC',
       'WALPOLE MTN VIEW WINERY', 'GILMANTON WINERY & VINEYARD',
       'HAUNTING WHISPER VYDS', 'STAR INDUSTRIES INC.',
       'LOYAL DOG WINERY', 'R.P.IMPORTS INC', 'THE PIERPONT GROUP LLC',
       'APPOLO VINEYARDS LLC', 'BLACK ROCK SPIRITS LLC',
       'CENTEUR IMPORTS LLC', 'HIGHLAND WINE MERCHANTS LLC',
       'AMERICAN SPIRITS EXCHANGE', 'UNCORKED', 'BRONCO WINE COMPANY',
       'MILTONS DISTRIBUTING CO', 'TRUETT HURST', 'LAUREATE IMPORTS CO',
       'FANTASY FINE WINES CORP', 'AAPER ALCOHOL & CHEMICAL CO',
       'SILVER MOUNTAIN CIDERS', 'CAPSTONE INTERNATIONAL',
       'FLAVOR ESSENCE INC'], dtype=object)

In [39]:
vendor_sales_summary['volume']= vendor_sales_summary['volume'].astype('float64')

In [40]:
vendor_sales_summary.fillna(0, inplace =True)

In [41]:
vendor_sales_summary['VendorName'] = vendor_sales_summary['VendorName'].str.strip()